 
EMMC_DEVICE="mmcblk2"
EMMC_PARTITION_DEVICE="${EMMC_DEVICE}p1"
EMMC_PARTITION_LABEL="BOOT"
EMMC_PARTITION_START="32MiB"
EMMC_PARTITION_END="544MiB"

NVME_NAME="nvme0"
NVME_DEVICE="${NVME_NAME}n1"
NVME_PARTITION_DEVICE="${NVME_DEVICE}p1"
NVME_PARTITION_NAME="${NVME_PARTITION_DEVICE}_luks"
NVME_PARTITION_START="0%"
NVME_PARTITION_END="100%"
NVME_VOLUMEGROUP_NAME="${NVME_PARTITION_NAME}_lvm"

#ROOT_VOLUME_LABEL="ROOT"
ROOT_VOLUME_NAME="${NVME_VOLUMEGROUP_NAME}_root"
ROOT_VOLUME_SIZE="100%FREE"

SWAP_VOLUME_LABEL="SWAP"
SWAP_VOLUME_NAME="${NVME_VOLUMEGROUP_NAME}_swap"
SWAP_VOLUME_SIZE="8GiB"



cryptsetup open "/dev/${NVME_PARTITION_DEVICE}" "$NVME_PARTITION_NAME"


#mkdir -p /tmp/boot
mkdir -p /tmp/root

sleep 3
#mount "/dev/${EMMC_PARTITION_DEVICE}" /tmp/boot
mount "/dev/${NVME_VOLUMEGROUP_NAME}/${ROOT_VOLUME_NAME}" /tmp/root

